@extends('Website._master')
@section('page_title', 'Your local markets')
@section('body')
<div class="ml-container discovery-page"><nav class="discovery-breadcrumb" aria-label="Breadcrumb"><a href="{{ url('/') }}">Home</a><span>/</span><span>Markets</span></nav>
<header class="discovery-hero"><div><span class="shop-kicker">GOOD FOOD. GREAT NEIGHBORHOODS.</span><h1>Make room for<br><em>market mornings.</em></h1><p>Find your local gathering place. Meet the growers.<br>Bring home something good.</p><a href="#market-directory" class="shop-pill">Find a market <span>↗</span></a></div>@include('Website.Partials.discovery-art')</header>
<div class="discovery-path"><span><b>01</b> Find your market</span><i>→</i><span><b>02</b> Meet a grower</span><i>→</i><span><b>03</b> Pick your produce</span></div>
@include('Website.Partials.alerts')
<section id="market-directory" class="discovery-workspace">@include('Website.Partials.discovery-filters',['mode'=>'markets','action'=>url('/markets')])<div><div class="shop-section-heading"><div><span class="shop-kicker">EXPLORE YOUR AREA</span><h2>A good place to start.</h2></div><span class="discovery-count">{{ $markets->total() }} {{ \Illuminate\Support\Str::plural('market',$markets->total()) }}</span></div><div class="discovery-market-grid">@forelse($markets as $market)<article class="market-discovery-card"><a class="market-card-art" href="{{ url('/markets/'.$market->id) }}" aria-label="Explore {{ $market->name }}"><i class="fa-solid fa-store"></i><span>{{ $market->city }}</span><b>↗</b></a><div class="market-card-copy"><span class="shop-kicker">{{ $market->state }} · {{ $market->country }}</span><h3><a href="{{ url('/markets/'.$market->id) }}">{{ $market->name }}</a></h3><p>{{ $market->address }}</p><div class="market-card-facts"><span><i class="fa-regular fa-calendar"></i> {{ $market->operating_days }}</span><span><i class="fa-regular fa-clock"></i> {{ substr($market->start_time,0,5) }} – {{ substr($market->end_time,0,5) }}</span><span><i class="fa-solid fa-seedling"></i> {{ $market->market_farmers_count }} participating growers</span></div><a class="shop-outline" href="{{ url('/markets/'.$market->id) }}">Explore this market <span>↗</span></a></div></article>@empty<div class="discovery-empty"><i class="fa-solid fa-map-location-dot"></i><h3>No markets found here yet.</h3><p>Try another location or a different market day.</p><a href="{{ url('/markets') }}" class="shop-outline">Clear filters ↗</a></div>@endforelse</div>@include('Website.Partials.pagination',['paginator'=>$markets])</div></section></div>
@endsection
