@extends('Website._master')
@section('page_title', $market->name)
@section('body')
<div class="ml-container discovery-page"><nav class="discovery-breadcrumb" aria-label="Breadcrumb"><a href="{{ url('/markets') }}">← All markets</a><span>/</span><span>{{ $market->city }}</span><span>/</span><span>{{ $market->name }}</span></nav><header class="discovery-hero market-detail-hero"><div><span class="shop-kicker">YOUR {{ strtoupper($market->city) }} MARKET DAY</span><h1>{{ $market->name }}<em>A local connection.</em></h1><p><i class="fa-solid fa-location-dot"></i> {{ $market->address }}, {{ $market->city }}, {{ $market->state }}</p><div class="discovery-actions"><a class="shop-pill" href="#market-growers">Meet the growers <span>↗</span></a><a class="shop-outline" href="#directions">Find this market <i class="fa-solid fa-location-arrow"></i></a></div></div>@include('Website.Partials.discovery-art')</header>
<div class="market-information"><div><i class="fa-regular fa-calendar"></i><span>MARKET DAYS<strong>{{ $market->operating_days }}</strong></span></div><div><i class="fa-regular fa-clock"></i><span>STALL HOURS<strong>{{ substr($market->start_time,0,5) }} – {{ substr($market->end_time,0,5) }}</strong></span></div><div><i class="fa-solid fa-seedling"></i><span>LOCAL GROWERS<strong>{{ $farmerCount }} participating</strong></span></div><div><i class="fa-solid fa-basket-shopping"></i><span>THE CURRENT HARVEST<strong>{{ $productCount }} products</strong></span></div></div>
<section class="discovery-section" id="market-growers"><div class="shop-section-heading"><div><span class="shop-kicker">GOOD PEOPLE. GOOD PRODUCE.</span><h2>The faces of this market.</h2></div><a href="{{ url('/farmers').'?market_id='.$market->id }}" class="shop-outline">Search all growers ↗</a></div><div class="market-grower-carousel" tabindex="0" aria-label="Growers at this market">@forelse($farmers as $farmer)@include('Website.Partials.discovery-farmer',['compact'=>true])@empty<div class="discovery-empty"><h3>The next gathering is taking shape.</h3><p>No participating growers are listed for this market yet.</p><a href="{{ url('/farmers') }}" class="shop-outline">Meet other growers ↗</a></div>@endforelse</div></section>
<div class="discovery-two-column">@include('Website.Partials.discovery-map',['place'=>$market])<section class="discovery-panel"><span class="shop-kicker">PLAN YOUR MARKET MOMENT</span><h2>Upcoming pickups.</h2><p>Choose a grower and select your available time at checkout. Times shown in {{ config('app.timezone') }}.</p>@forelse($pickupSlots as $slot)<a class="discovery-slot" href="{{ url('/farmers/'.$slot->farmer_id) }}"><span class="slot-date"><b>{{ $slot->date->format('d') }}</b>{{ $slot->date->format('M') }}</span><span><strong>{{ $slot->farmer?->stall_name }}</strong><small>{{ $slot->date->format('D') }} · {{ substr($slot->start_time,0,5) }} – {{ substr($slot->end_time,0,5) }}</small></span><i class="fa-solid fa-arrow-up-right-from-square"></i></a>@empty<div class="discovery-empty compact"><i class="fa-regular fa-calendar"></i><p>Pickup windows are being prepared. Check a grower profile before planning your visit.</p></div>@endforelse<a class="discovery-text-link" href="{{ url('/pickup-guidelines') }}">Your guide to market pickup ↗</a></section></div>
<section class="discovery-section"><div class="shop-section-heading"><div><span class="shop-kicker">FROM THIS MARKET TO YOUR TABLE</span><h2>A taste of what is here.</h2></div><a href="{{ url('/products').'?market_id='.$market->id }}" class="shop-outline">Shop this market ↗</a></div><div class="discovery-product-grid">@forelse($products as $product)@include('Website.Partials.shop-product')@empty<div class="discovery-empty"><h3>A new harvest is on its way.</h3><p>Come back for current stock from this market.</p></div>@endforelse</div></section></div>
@endsection
