<?php $__env->startSection('page_title', 'Good food, close to home'); ?>
<?php $__env->startSection('page_styles'); ?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@14.2.0/swiper-bundle.min.css">
<link rel="stylesheet" href="<?php echo e(asset('Assets/Website_Asset/css/home.css')); ?>">
<?php $__env->stopSection(); ?>
<?php $__env->startSection('body'); ?>
<div class="home-page">
    <section class="home-hero" aria-labelledby="home-title">
        <div class="ml-container home-hero-inner">
            <div class="home-hero-heading"><span class="shop-kicker">THE NEIGHBOURHOOD HARVEST</span><h1 id="home-title">Fresh finds.<br><em>Closer connections.</em></h1><p>Your local growers. Their seasonal best.<br>A basket worth making a market morning for.</p></div>
            <div class="home-stage" aria-hidden="true">
                <span class="home-giant-word">FRESH</span><span class="home-orbit"></span>
                <img class="home-basket" src="<?php echo e(asset('Assets/Website_Asset/images/home-harvest-basket.png')); ?>" alt="" width="1280" height="1280" fetchpriority="high">
                <img class="home-ingredient ingredient-one" src="<?php echo e(asset('Assets/Website_Asset/images/home-floating-tomato.png')); ?>" alt="" width="1280" height="1280">
                <img class="home-ingredient ingredient-two" src="<?php echo e(asset('Assets/Website_Asset/images/home-floating-tomato.png')); ?>" alt="" width="1280" height="1280">
                <i class="fa-solid fa-leaf home-ingredient ingredient-leaf-one"></i><i class="fa-solid fa-leaf home-ingredient ingredient-leaf-two"></i>
                <span class="home-handwritten">Good things<br>grow locally.</span><span class="home-stamp">PICK ONLINE<br><i class="fa-solid fa-basket-shopping"></i><br>PAY AT THE STALL</span>
            </div>
            <div class="home-hero-bottom"><div><a href="<?php echo e(url('/products')); ?>" class="shop-pill">Build your fresh basket <span>↗</span></a><a href="<?php echo e(url('/markets')); ?>" class="home-text-link">Find a local market <span>↗</span></a></div><p><i class="fa-solid fa-store" aria-hidden="true"></i> Pre-order. Meet your grower. Collect.</p><button type="button" class="home-motion-toggle" data-home-motion hidden aria-pressed="false"><i class="fa-solid fa-pause" aria-hidden="true"></i> Pause motion</button></div>
        </div>
    </section>
    <div class="home-ribbon"><span><i class="fa-solid fa-seedling" aria-hidden="true"></i> Seasonal discoveries</span><span><i class="fa-solid fa-location-dot" aria-hidden="true"></i> Local market pickup</span><span><i class="fa-solid fa-handshake" aria-hidden="true"></i> Pay your grower in person</span></div>

    <section class="home-section home-categories" aria-labelledby="home-categories-title">
        <div class="ml-container home-heading centered"><span class="shop-kicker">LET YOUR APPETITE WANDER</span><h2 id="home-categories-title">A little of <em>what you love.</em></h2><p>Explore the season, one fresh discovery at a time.</p></div>
        <div class="ml-container home-category-tabs"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e(url('/products').'?category_id='.$category->id); ?>"><?php echo e($category->name); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><a href="<?php echo e(url('/products')); ?>">All the goodness ↗</a></div>
        <div class="swiper home-category-slider" aria-label="Explore product categories"><div class="swiper-wrapper">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <?php ($categoryPhoto = match (true) {
                str_contains(strtolower($category->name), 'fruit') => 'fruits/Fresh-apple.png',
                str_contains(strtolower($category->name), 'veget') => 'vegetables/carrot.jpg',
                str_contains(strtolower($category->name), 'grain') => 'grains/rice.jpg',
                default => 'vegetables/mix.jpg'
            }); ?>
            <a class="swiper-slide home-category-slide" href="<?php echo e(url('/products').'?category_id='.$category->id); ?>"><img src="<?php echo e(asset('Assets/Website_Asset/images/'.$categoryPhoto)); ?>" alt="" loading="lazy" width="600" height="600"><span class="home-category-caption"><small><?php echo e($category->products_count); ?> available picks</small><strong><?php echo e($category->name); ?></strong><span aria-hidden="true">↗</span></span></a>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="swiper-slide home-category-slide"><img src="<?php echo e(asset('Assets/Website_Asset/images/vegetables/mix.jpg')); ?>" alt="Fresh seasonal vegetables" loading="lazy"><span class="home-category-caption"><strong>A new season is coming.</strong></span></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </div></div>
        <div class="home-slider-controls" data-category-controls hidden><button type="button" class="home-category-prev" aria-label="Previous category">←</button><span>FIND YOUR FRESH</span><button type="button" class="home-category-next" aria-label="Next category">→</button></div>
    </section>

    <section class="ml-container home-section home-products" aria-labelledby="home-products-title"><div class="home-heading"><div><span class="shop-kicker">THE CURRENT HARVEST</span><h2 id="home-products-title">Fresh picks.<br><em>Good days ahead.</em></h2></div><a href="<?php echo e(url('/products')); ?>" class="home-text-link">Shop the whole harvest <span>↗</span></a></div><div class="home-product-grid"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php echo $__env->make('Website.Partials.shop-product',['product'=>$product], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>The growers are preparing their next harvest. Check back for fresh stock soon.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></section>

    <section class="home-market-section"><div class="ml-container home-section home-market-layout"><div class="home-market-intro"><span class="shop-kicker">YOUR NEXT LOCAL STOP</span><h2>A place to meet.<br><em>A reason to return.</em></h2><p>Make a little time for market day. Find your local spot, meet the growers and bring home something good.</p><a href="<?php echo e(url('/markets')); ?>" class="shop-pill">Explore the markets <span>↗</span></a><div class="home-stall-art" aria-hidden="true"><i class="fa-solid fa-store"></i><span>See you<br><em>at the stall.</em></span></div></div><div class="home-market-list"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $markets; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $market): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(url('/markets/'.$market->id)); ?>"><span class="home-market-number">0<?php echo e($loop->iteration); ?></span><div><small><i class="fa-solid fa-location-dot" aria-hidden="true"></i> <?php echo e($market->city); ?></small><h3><?php echo e($market->name); ?></h3><p><?php echo e($market->operating_days); ?><br><?php echo e(substr($market->start_time,0,5)); ?> – <?php echo e(substr($market->end_time,0,5)); ?></p></div><span class="home-market-arrow" aria-hidden="true">↗</span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>New market locations will appear here when they’re added.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div></section>

    <section class="ml-container home-section home-story"><div class="home-story-photo"><img src="<?php echo e(asset('Assets/Website_Asset/images/vegetables/mix.jpg')); ?>" alt="A colourful selection of vegetables at a local market" width="612" height="405" loading="lazy"><span>Small stalls.<br><em>Shared stories.</em></span></div><div><span class="shop-kicker">MORE THAN A BASKET</span><h2>Know your food.<br><em>Meet your people.</em></h2><p>MarketLink brings the local market online, while keeping its best part in person. Farmers share their stock. You plan your basket. The connection happens at the stall.</p><ol class="home-simple-steps"><li><b>01</b> Discover a grower & their harvest.</li><li><b>02</b> Pre-order & choose a pickup window.</li><li><b>03</b> Collect at the market & pay directly.</li></ol><a href="<?php echo e(url('/about')); ?>" class="home-text-link">A little more about us <span>↗</span></a></div></section>

    <section class="home-section home-reviews" aria-labelledby="home-reviews-title"><div class="ml-container home-heading centered"><span class="shop-kicker">WORDS FROM THE COMMUNITY</span><h2 id="home-reviews-title">Local food.<br><em>Lasting impressions.</em></h2><p>Recent published reviews, straight from our grower profiles.</p></div>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($reviews->isNotEmpty()): ?><div class="swiper home-review-slider" aria-label="Community reviews"><div class="swiper-wrapper"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $reviews; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $review): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="swiper-slide home-review-slide"><i class="fa-solid fa-quote-left home-quote" aria-hidden="true"></i><blockquote><?php echo e($review->comment); ?></blockquote><span class="home-review-stars" aria-label="<?php echo e($review->rating); ?> out of 5 stars"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php for($star=1;$star<=5;$star++): ?><i class="<?php echo e($star <= $review->rating ? 'fa-solid' : 'fa-regular'); ?> fa-star" aria-hidden="true"></i><?php endfor; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></span><div class="home-review-person"><span aria-hidden="true"><?php echo e(mb_substr($review->user->name,0,1)); ?></span><div><strong><?php echo e($review->user->name); ?></strong><a href="<?php echo e(url('/farmers/'.$review->farmer_id).'#grower-reviews'); ?>"><?php echo e($review->farmer->stall_name); ?> ↗</a></div></div></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><div class="home-slider-controls" data-review-controls hidden><button type="button" class="home-review-prev" aria-label="Previous community review">←</button><button type="button" data-review-play aria-label="Play automatic reviews"><i class="fa-solid fa-play" aria-hidden="true"></i></button><button type="button" class="home-review-next" aria-label="Next community review">→</button></div><?php else: ?><p class="home-review-empty">Every market visit has a story. Community reviews will appear here when they’re published.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </section>

    <section class="ml-container home-final"><div><span class="shop-kicker">MAKE YOUR NEXT BASKET LOCAL</span><h2>Good things are<br><em>growing near you.</em></h2><p>Find your favourites. Choose your pickup. See you at the market.</p></div><div><a href="<?php echo e(url('/products')); ?>" class="shop-pill">Explore fresh produce <span>↗</span></a><a href="<?php echo e(route('register')); ?>" class="home-text-link">Have a harvest to share? Join us <span>↗</span></a></div><i class="fa-solid fa-seedling" aria-hidden="true"></i></section>
</div>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('page_scripts'); ?>
<script src="https://cdn.jsdelivr.net/npm/swiper@14.2.0/swiper-bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>
<script src="<?php echo e(asset('Assets/Website_Asset/js/home.js')); ?>" defer></script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('Website._master', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\Marketlink\resources\views/Website/Home/index.blade.php ENDPATH**/ ?>