<section class="customer-panel discovery-panel" aria-labelledby="discovery-heading">
    <div class="customer-section-heading"><div><span class="customer-eyebrow">GOOD THINGS, CLOSE BY</span><h2 id="discovery-heading">Take the local route.</h2></div><span class="discovery-icon"><i class="fa-solid fa-map-location-dot"></i></span></div><p class="customer-muted">Find a market or meet a grower. Select a place to explore its location.</p>
    @if($mapPlaces->isNotEmpty())
        <label for="dashboard-map-place" class="customer-field-label">Markets & farm stalls</label><select id="dashboard-map-place" class="customer-select">@foreach($mapPlaces as $place)<option value="{{ $loop->index }}">{{ $place['name'] }} · {{ $place['city'] }} · {{ $place['kind'] }}</option>@endforeach</select>
        <div class="customer-map"><iframe id="dashboard-map" title="Selected market or farm stall on OpenStreetMap" loading="lazy" referrerpolicy="no-referrer" src="https://www.openstreetmap.org/export/embed.html?{{ http_build_query(['bbox' => implode(',', [$mapPlaces[0]['longitude'] - .018, $mapPlaces[0]['latitude'] - .012, $mapPlaces[0]['longitude'] + .018, $mapPlaces[0]['latitude'] + .012]), 'layer' => 'mapnik', 'marker' => $mapPlaces[0]['latitude'].','.$mapPlaces[0]['longitude']]) }}"></iframe></div>
        <div class="map-place-details"><span class="map-place-icon"><i class="fa-solid fa-location-dot"></i></span><div><a id="map-place-name" href="{{ $mapPlaces[0]['url'] }}">{{ $mapPlaces[0]['name'] }}</a><span id="map-place-address">{{ $mapPlaces[0]['address'] }}, {{ $mapPlaces[0]['city'] }}</span></div></div><a id="map-directions" class="customer-button customer-button-light" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/dir/?api=1&amp;destination={{ urlencode($mapPlaces[0]['latitude'].','.$mapPlaces[0]['longitude']) }}">Get pickup directions <i class="fa-solid fa-location-arrow"></i></a><p class="map-help">Choose your starting point in Maps.</p>
        <script type="application/json" id="dashboard-map-data">{!! json_encode($mapPlaces, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
    @else
        <div class="customer-empty compact"><i class="fa-solid fa-map-location-dot"></i><p>Map locations are being added. Explore the directory for addresses and opening times.</p><a href="{{ url('/markets') }}" class="customer-text-link">Browse markets ↗</a></div>
    @endif
</section>
