<section class="customer-panel favorites-panel" aria-labelledby="favorites-heading"><div class="customer-section-heading"><div><span class="customer-eyebrow">KEEP YOUR GOOD THINGS CLOSE</span><h2 id="favorites-heading">Your saved little favorites.</h2></div><div class="customer-carousel-actions"><button type="button" class="customer-icon-button" data-carousel-target="saved-carousel" data-carousel-direction="-1" aria-label="Previous favorites">←</button><button type="button" class="customer-icon-button" data-carousel-target="saved-carousel" data-carousel-direction="1" aria-label="Next favorites">→</button><a href="{{ route('customer_favorites') }}" class="customer-text-link">View all ↗</a></div></div>
    <div class="customer-carousel" id="saved-carousel" tabindex="0" aria-label="Saved farmers and products">
        @forelse($savedFavorites as $favorite)
            @if($favorite->product)
                @php($savedProduct = $favorite->product)
                <article class="saved-card"><a class="saved-card-image" href="{{ url('/products/'.$savedProduct->id) }}"><img src="{{ $savedProduct->imageUrl() }}" alt="{{ $savedProduct->name }}" loading="lazy"><span><i class="fa-solid fa-heart"></i></span></a><div class="saved-card-body"><span class="stock-label {{ $savedProduct->is_active && $savedProduct->stock_quantity > 0 ? '' : 'stock-unavailable' }}">{{ $savedProduct->is_active && $savedProduct->stock_quantity > 0 ? $savedProduct->stock_quantity.' '.$savedProduct->unit.' available' : 'Currently unavailable' }}</span><h3>{{ $savedProduct->name }}</h3><p>{{ $savedProduct->farmer?->stall_name }}</p><a href="{{ url('/products/'.$savedProduct->id) }}" class="saved-card-link"><strong>Rs. {{ number_format($savedProduct->price) }} <small>/ {{ $savedProduct->unit }}</small></strong><span>↗</span></a></div></article>
            @elseif($favorite->farmer)
                <article class="saved-card saved-grower"><div class="saved-grower-art" aria-hidden="true"><span class="grower-monogram">{{ mb_substr($favorite->farmer->stall_name, 0, 1) }}</span><i class="fa-solid fa-seedling"></i></div><div class="saved-card-body"><span class="stock-label {{ $favorite->farmer->available_products_count ? '' : 'stock-unavailable' }}">{{ $favorite->farmer->available_products_count ? $favorite->farmer->available_products_count.' fresh picks in stock' : 'Waiting for the next harvest' }}</span><h3>{{ $favorite->farmer->stall_name }}</h3><p><i class="fa-solid fa-location-dot"></i> {{ $favorite->farmer->city }}</p><a class="saved-card-link" href="{{ url('/farmers/'.$favorite->farmer->id) }}"><strong>Visit your grower</strong><span>↗</span></a></div></article>
            @endif
        @empty
            <div class="customer-empty compact"><i class="fa-regular fa-heart"></i><h3>Make room for your favorites.</h3><p>Your bookmarked products and growers will live here, with their current stock availability.</p><a href="{{ url('/farmers') }}" class="customer-text-link">Discover growers ↗</a></div>
        @endforelse
    </div>
</section>
<section class="customer-panel reorder-panel" aria-labelledby="reorder-heading"><div class="customer-section-heading"><div><span class="customer-eyebrow">LOVED IT LAST TIME?</span><h2 id="reorder-heading">Bring back the goodness.</h2></div><span class="customer-muted">Your past picks. Today's prices.</span></div><div class="customer-carousel" tabindex="0" aria-label="Previously purchased items">
    @forelse($reorderItems as $item)
        <article class="reorder-card"><img src="{{ $item->product->imageUrl() }}" alt="{{ $item->product->name }}" loading="lazy"><div><h3>{{ $item->product->name }}</h3><p>{{ $item->quantity }} {{ $item->product->unit }} · Rs. {{ number_format($item->product->price * $item->quantity) }}</p><span>{{ $item->product->farmer?->stall_name }}</span></div><form action="{{ route('customer_reorder', $item) }}" method="POST">@csrf<button class="customer-icon-button" type="submit" aria-label="Reorder {{ $item->product->name }}" @disabled($item->product->stock_quantity < $item->quantity)><i class="fa-solid fa-arrow-rotate-right"></i></button></form>@if($item->product->stock_quantity < $item->quantity)<small class="reorder-unavailable">Not enough stock for this quantity</small>@endif</article>
    @empty
        <div class="customer-empty compact"><i class="fa-solid fa-arrow-rotate-right"></i><p>After your first completed pickup, reorder your favorites here with one click.</p></div>
    @endforelse
</div></section>
