@extends('Website.Dashboard._layout')
@section('page_title', 'My pre-orders')
@section('banner_title', 'Good things, on the way.')
@section('banner_text', 'From your first fresh pick to your next market morning.')
@section('banner_icon', 'fa-bag-shopping')
@section('account_content')
<nav class="account-filters" aria-label="Filter pre-orders">@foreach([''=>'All pre-orders','active'=>'Active','pending'=>'Placed','confirmed'=>'Accepted','ready'=>'Ready for pickup','picked_up'=>'Completed','cancelled'=>'Cancelled'] as $status=>$label)<a class="{{ request('status', '') === $status ? 'is-selected' : '' }}" href="{{ route('customer_orders', $status ? ['status'=>$status] : []) }}">{{ $label }} <span>{{ $status === 'active' ? collect($statusCounts)->only(['pending','confirmed','ready'])->sum() : ($status ? ($statusCounts[$status] ?? 0) : $statusCounts->sum()) }}</span></a>@endforeach</nav>
<div class="account-order-grid">@forelse($orders as $order)<article class="customer-panel"><div class="pickup-order-heading"><span class="order-number">PRE-ORDER #{{ $order->id }}</span><span class="customer-status status-{{ $order->status }}">{{ $order->statusLabel() }}</span></div><h2 class="account-card-title">{{ $order->farmer?->stall_name ?? 'Your local grower' }}</h2><p class="customer-muted">{{ $order->pickupSlot?->date?->format('D, d M Y') ?? 'Pickup date to be confirmed' }}<br>{{ $order->pickupSlot ? substr($order->pickupSlot->start_time,0,5).' – '.substr($order->pickupSlot->end_time,0,5).' '.config('app.timezone') : '' }}</p><p><i class="fa-solid fa-location-dot"></i> {{ $order->pickupSlot?->market?->name ?? 'Ask your grower for the pickup location' }}</p><div class="pickup-order-summary"><span>{{ $order->items->sum('quantity') }} items · Pay at pickup</span><strong>Rs. {{ number_format($order->total_amount) }}</strong></div><a class="customer-button" href="{{ route('customer_order_detail',$order) }}">View pre-order <span>↗</span></a></article>@empty<div class="customer-panel customer-empty"><i class="fa-solid fa-basket-shopping"></i><h2>A fresh start.</h2><p>No pre-orders in this view yet.</p><a href="{{ url('/products') }}" class="customer-button">Explore the harvest ↗</a></div>@endforelse</div>@include('Website.Partials.pagination',['paginator'=>$orders])
@endsection
