@extends('Website.Dashboard._layout')
@section('page_title', 'Pre-order details')
@section('banner_title', 'Your next market moment.')
@section('banner_text', 'Everything you need for a smooth pickup, in one place.')
@section('banner_icon', 'fa-store')
@section('account_content')
<a class="customer-text-link account-back" href="{{ route('customer_orders') }}">← All pre-orders</a>
<div id="order-detail" class="customer-main-grid"><section class="customer-panel"><div class="pickup-order-heading"><h2>Pre-order #{{ $order->id }}</h2><span class="customer-status status-{{ $order->status }}">{{ $order->statusLabel() }}</span></div><p class="customer-muted">Placed {{ $order->order_date?->format('d M Y') }}</p>
@if($order->status !== 'cancelled')@php($stage = array_search($order->status,['pending','confirmed','ready','picked_up']))<ol class="pickup-progress" aria-label="Order progress">@foreach(['Placed','Accepted','Ready for pickup','Completed'] as $step)<li class="{{ $loop->index <= $stage ? 'is-complete' : '' }}" @if($loop->index === $stage) aria-current="step" @endif><span>{{ $loop->iteration }}</span>{{ $step }}</li>@endforeach</ol>@endif
@foreach($order->items as $item)<article class="account-item">@if($item->product)<a href="{{ url('/products/'.$item->product_id) }}"><img src="{{ $item->product->imageUrl() }}" alt="{{ $item->product->name }}"></a>@endif<div><h3>{{ $item->product?->name ?? 'Unavailable product' }}</h3><p>{{ $item->quantity }} {{ $item->product?->unit }} × Rs. {{ number_format($item->price) }}</p><strong>Rs. {{ number_format($item->subtotal) }}</strong>@if($order->status === 'picked_up' && $item->product)<form method="POST" action="{{ route('customer_reorder',$item) }}" data-ajax>@csrf<button class="customer-button customer-button-light customer-button-small" @disabled(!$item->product->is_active || $item->product->stock_quantity < $item->quantity)>Add again ↗</button></form>@endif</div></article>@endforeach
<div class="pickup-order-summary"><span>{{ $order->status === 'picked_up' ? 'Collected & paid in person' : 'Pay your grower at pickup' }}</span><strong>Rs. {{ number_format($order->total_amount) }}</strong></div>@if($order->notes)<h3>Your note</h3><p>{{ $order->notes }}</p>@endif
@if($order->status === 'picked_up')<a href="{{ route('customer_reviews') }}" class="customer-button">Share your experience ↗</a>@endif</section>
<aside class="customer-right-column"><section class="customer-panel"><span class="customer-eyebrow">MEET YOU AT THE STALL</span><h2>{{ $order->farmer?->stall_name ?? 'Your grower' }}</h2><p class="customer-muted">{{ $order->farmer?->user?->name }}</p><div class="account-pickup-box"><i class="fa-regular fa-calendar"></i><strong>{{ $order->pickupSlot?->date?->format('D, d M Y') ?? 'Date to be confirmed' }}</strong><p>{{ $order->pickupSlot ? substr($order->pickupSlot->start_time,0,5).' – '.substr($order->pickupSlot->end_time,0,5).' '.config('app.timezone') : 'Time to be confirmed' }}</p><strong>{{ $order->pickupSlot?->market?->name }}</strong><p>{{ $order->pickupSlot?->market?->address }}</p></div><div class="account-actions"><a class="customer-button customer-button-light" href="{{ url('/farmers/'.$order->farmer_id) }}">Meet your grower ↗</a>@if($market = $order->pickupSlot?->market)<a class="customer-button" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/dir/?api=1&destination={{ urlencode($market->name.', '.$market->address.', '.$market->city) }}">Pickup directions ↗</a>@endif</div></section><section class="customer-panel"><h3>Plans changed?</h3><p class="customer-muted">Cancel before pickup starts, unless your grower has already marked the order ready.</p><form method="POST" action="{{ route('customer_order_cancel',$order) }}" data-ajax data-confirm="Cancel this pre-order? Your grower will see its updated status." data-ajax-refresh="#order-detail">@csrf<button class="customer-button customer-button-light" @disabled(!$order->canCancel())>Cancel pre-order</button></form>@unless($order->canCancel())<p class="cancellation-note">Cancellation is closed for this pre-order.</p>@endunless</section></aside></div>
@endsection
